project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 404.qmd
  resources:
    - assets/**
    - cv/**
    - CNAME
    - .nojekyll
    - robots.txt

website:
  title: "Georgiy (Gosha) Syunyaev"
  site-url: https://gsyunyaev.com
  description: "Assistant Professor of Political Science at Vanderbilt University. Research on propaganda, media, and politics in autocracies."
  image: assets/img/profile_pic_web.jpg
  open-graph: true
  twitter-card:
    card-style: summary
  favicon: assets/img/favicon.png
  google-analytics: "G-3DSHY26B52"
  search: false

format:
  html:
    minimal: true
    css: styles.css
    include-in-header: _includes/head.html
    lang: en
    toc: false
    anchor-sections: false

execute:
  echo: false
  warning: false
  message: false
